---
- include: user.yml

- name: Ensure nexus is installed.
  stat: path="{{ nexus_home_dir }}/bin/nexus"
  register: installed

- include: download.yml
  when: installed.stat.exists == false or nexus_update

- include: installation.yml

- include: configuration.yml

- include: initd.yml

- name: Main -  Clean-up
  include: cleanup.yml
  when: nexus_cleanup == true

- name: install nexus.service
  template:
    src: nexus.service.j2
    dest: /lib/systemd/system/nexus.service
    owner: root
    group: root
    mode: 0644
  notify: restart nexus servic

- name: Enamble and start
  systemd:
    state: started
    enabled: yes
    daemon_reload: yes
    name: nexus

