---
- import_tasks: user.yml

- name: Ensure nexus is installed.
  stat: path="{{ nexus_home_dir }}/bin/nexus"
  register: installed

- import_tasks: download.yml
  when: installed.stat.exists == false or nexus_update

- import_tasks: installation.yml

- import_tasks: configuration.yml

- import_tasks: initd.yml

- name: Main -  Clean-up
  import_tasks: cleanup.yml
  when: nexus_cleanup == true

- name: install nexus.service
  template:
    src: nexus.service.j2
    dest: /lib/systemd/system/nexus.service
    owner: root
    group: root
    mode: 0644
  notify: restart nexus service

- name: Enable and start
  systemd:
    state: started
    enabled: yes
    daemon_reload: yes
    name: nexus

